### ISSUE TITLE
Rotationmap fit_map method, error using "shadowed" parameter.

### ISSUE THREAD

**Issue by franciscourbina** [richteague/eddy#25]
Hello Dr. Richard. I'm Francisco Urbina, an astronomy student from Chile, currently working as an intern for the NRAO. I was trying to use eddy for my research project in debris disks, but got an error I couldn't fix and I don't know if it is an usual one or maybe it's something different. I'll copy the code I've been using and the error on a txt file. 

[error.txt](https://github.com/richteague/eddy/files/8121354/error.txt)

In case you are wondering, I'm using python 3.9.7 and anaconda for package managenement. 

Thanks in advance for your reply.

**Comment by richteague** [comment]
Hi Francisco! I think I understand where your error comes from (probably my bad choices in setting the default parameters for the warp model). Just to confirm, you still get the same error when you set `params['shadowed']=False`? If so, I'll try and push an update later today to fix that.

**Comment by franciscourbina** [comment]
Everything works fine when using params['shadowed']=False.  
Thanks!

**Comment by richteague** [comment]
Great, I found the issue and fixed it. You should use `pip install astro-eddy --upgrade` and you should get version 2.1.4-1 where the issue is fixed. Please let me know if that works for you!

**Comment by franciscourbina** [comment]
Now it's working! Thanks for your quick answers.
Hope you have a good week. 
Cheers.
