### ISSUE TITLE
'rotationmap' import error

### ISSUE THREAD

**Issue by 20skarthikeyan01** [richteague/eddy#27]
Hello Dr. Teague! My name is Shreya Karthikeyan, and I am using the package eddy for my research at the University of Florida on protoplanetary disks. I've been able to utilize other packages of yours with no problem, but I've been running into an issue with the 'rotationmap' class in eddy. I installed eddy but rotationmap is simply not available when I list the available functions. Is this a common issue? Does it depend on the version of eddy that I installed?

Thank you in advance.

**Comment by richteague** [comment]
Hi @20skarthikeyan01, sorry for the slow reply. What's the error that comes up when you're trying to import `rotationmap`?

**Comment by richteague** [comment]
I assume this is fixed. If you're still having issues @20skarthikeyan01, please let me know!
