### ISSUE TITLE
missing default_parameters.yml on pip install

### ISSUE THREAD

**Issue by interstellarmedium** [richteague/eddy#29]
Hi Richard, I'm having my class use eddy in a problem set for a planet formation seminar but they were having problems with it. I just uninstalled and installed it again to see if I could reproduce their problem and I now find it broken too! It is missing the default_parameters.yml file. (If I get this file from github directly and copy it to the eddy directory in site-packages, all is fine but this is probably not what you want.)

Anyway, thanks for a very cool package!

**Comment by richteague** [comment]
Hi Jonathan! Can you try reinstalling from pip to see if the fix I just pushed works?

**Comment by richteague** [comment]
This looks like it should be fixed.
