### ISSUE TITLE
gaussian_ensemble crashes when specifying an optical depth

### ISSUE THREAD

**Issue by kevin-flaherty** [richteague/eddy#5]
When I try to create an ensemble of spectra using the gaussian_ensemble function, it works when when the optical depth tau is set to its default (None), but crashes whenever tau is set to a value. This is true regardless of the value. The error message that I get is

spectra,theta,velax = gaussian_ensemble(vrot=1500.,tau=5.0)                             
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-3214bfc99101> in <module>
----> 1 spectra,theta,velax = gaussian_ensemble(vrot=1500.,tau=5.0)

/Volumes/Untitled2/eddy/eddy/modelling.py in gaussian_ensemble(vrot, Tb, dV, tau, rms, dV_chan, N, oversample, PAmin, PAmax, linear_sample, plot, return_ensemble)
     68             spectra = np.array(spectra)
     69         else:
---> 70             spectra = _thick_line(velax[None, :], v_los[:, None], dV, Tex, tau)
     71     else:
     72         if oversample:

/Volumes/Untitled2/eddy/eddy/modelling.py in _thick_line(x, x0, dx, Tex, tau, N)
    232     """Optically thick line profile."""
    233     if not N:
--> 234         return Tex * (1. - np.exp(-_gaussian(x, x0, dx, tau, N=1)))
    235     xx = np.linspace(x[0], x[-1], x.size * int(N))
    236     yy = Tex * (1. - np.exp(-_gaussian(xx, x0, dx, tau, N=False)))

/Volumes/Untitled2/eddy/eddy/modelling.py in _gaussian(x, x0, dx, A, N)
    224     if not N:
    225         return A * np.exp(-np.power((x - x0) / dx, 2))
--> 226     xx = np.linspace(x[0], x[-1], x.size * int(N))
    227     yy = A * np.exp(-np.power((xx - x0) / dx, 2))
    228     return np.array([np.average(yy[i*N:(i+1)*N]) for i in range(x.size)])

~/anaconda2/envs/python3/lib/python3.7/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype)
    122     if num > 1:
    123         step = delta / div
--> 124         if step == 0:
    125             # Special handling for denormal numbers, gh-5437
    126             y /= div

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by richteague** [comment]
I think this way some poor array looping on my part. It should have been fixed now (at least I don't get any errors running the Notebooks).
