### ISSUE TITLE
Documentation for inferring rotation velocity from real data

### ISSUE THREAD

**Issue by kevin-flaherty** [richteague/eddy#6]
One thing that would be helpful in the Jupyter notebooks is an example, or more explicit description, of how to estimate the rotation velocity from actual data. The gaussian_ensemble class is very nice for testing the code, but once the testing is done the next step is to apply this to real data. The information on how to do this is contained throughout the various notebooks, but a section that explicitly lays out how to estimate rotation velocities from actual data would be a huge benefit for anyone trying to apply this code to their data. 

If it is easy, I would suggest using the TW Hya CO data that is already used in the 'Fitting Rotation Maps' notebook as an example in the 'Inferring Rotation Maps...' notebooks to explicitly demonstrate how someone could create the necessary spectra, theta, and velax arrays, how to use these arrays to create an annulus object, and then how to use the annulus object to infer the rotation velocity. Barring this, a simple step-by-step list (e.g. (1) create an array of spectra at a range of azimuthal angles from your data with shape N x M, (2) make an array of the azimuthal angles with shape N, etc.) would help someone that is skimming the notebooks looking for instructions on how to apply this code to their data.

**Comment by richteague** [comment]
This is something I spent a while debating and initially decided not to because it would require uploading another FITS cube which is both a large file and already publicly available. I can easily write a section including the specific steps one would need to extract the required arrays. Do you think that would be suitable?

**Comment by richteague** [comment]
I've updated Inferring Rotation Velocity with Gaussian Processes.ipynb to include a section with example code on how to go from a FITS cube to the arrays needed for the rotational velocity inference.

**Comment by kevin-flaherty** [comment]
I think a quick description of how to extract the necessary arrays, without including a large FITS file, is reasonable. The fact that cube.disk_coords returns r and theta values given an offset, inclination, and position angle (presumably assuming a flat disk) is really helpful, and I am glad that you mentioned that that feature exists. 

I wasn't able to get the rest of the code to work for extracting spectra/theta/velax (is the 'cube' variable mentioned when extracting spectra/theta/velax a 3D data cube, rather than the object created by rotationmap? how did you read it in so that it had similar dimensions as the downsampled and clipped object read in by rotationmap?). Providing this level of detail might be problematic anyways if you aren't going to provide a FITS file for someone to test with. Instead you could mention in words (rather than code) that the reader needs to extract spectra/theta/velax arrays from their data. Extracting spectra/theta/velax arrays is relatively straightforward once you know the r and theta value at each pixel, which your code provides. The only additional thing I think you should include is the exact format of the spectra/theta/velax arrays that is assumed by the annulus object (ie. spectra is an NxM array where N is the number of azimuthal points, and M is the number of channels). This would clarify the functionality of your code, as well as the fact that your code doesn't extend so far as to calculate spectra/theta/velax from someones dataset, but can interface with data once those parameters have been properly extracted.

**Comment by richteague** [comment]
I've tried to be a bit more explicit with the description of how to initialize `rotationmap` when using a 3D cube. I've tested the functions with a 3D cube and they all run through and give what's required.

I've also updated the docstrings in `fit_annulus` to be explicit for the shapes of the arrays needed.

**Comment by kevin-flaherty** [comment]
That all looks great. The only trouble I had was with:
`spectra=spectra.flatten()[:,mask].T`
which worked when I switched it to:
`spectra=spectra[:,mask].T`

Otherwise it all looks good to me.

**Comment by richteague** [comment]
Thanks for spotting!
